## YAML Template.
# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

before-script:
  - apt-get update -yqq
  - apt-get install git -yqq

  # Install phpunit, the tool that we will use for testing
  - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
  - chmod +x /usr/local/bin/phpunit

test:app:
  script:
  - phpunit --configuration phpunit.xml
# Install git (the php image doesn't have it) which is required by composer
