## YAML Template.
# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

before_script:
# Install git (the php image doesn't have it) which is required by composer
- apt-get update -yqq
- apt-get install git -yqq

# Install phpunit, the tool that we will use for testing
#- curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
#- chmod +x /usr/local/bin/phpunit
# cette solution installe la dernère version de phpunit et ne permet pas de la choisir

# Install composer
#- curl -sS https://getcomposer.org/installer | php
 
# Install all project dependencies
#- php composer.phar install

#test:classes:
#  script:
#  - vendor/bin/phpunit --configuration phpunit.xml

test:appweb:
  before_script:
  # Get and run selenium standalone server
  - apt-get update -yqq
  - apt-get install wget -yqq
  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
  - java -jar selenium-server-standalone-2.45.0.jar
  script:
  - vendor/bin/phpunit --configuration phpunit_selenium.xml
