## YAML Template.
# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

before_script:
# Install git (the php image doesn't have it) which is required by composer
- apt-get update -yqq
- apt-get install git -yqq

# Install phpunit, the tool that we will use for testing
#- curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
#- chmod +x /usr/local/bin/phpunit
# cette solution installe la dernère version de phpunit et ne permet pas de la choisir

# Install composer
- curl -sS https://getcomposer.org/installer | php
 
# Install all project dependencies
- php composer.phar install

test:classes:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml

test:appweb:
  before_script:
    # Install Java.
  - RUN \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    apt-get install -y oracle-java8-installer && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/oracle-jdk8-installer

    # Define working directory.
  - WORKDIR /data

# Define commonly used JAVA_HOME variable
  - ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
  # Run selenium standalone server
  - java -jar selenium-server-standalone-2.53.1.jar -Dwebdriver.chrome.driver=chromedriver.exe
  script:
  - vendor/bin/phpunit --configuration phpunit_selenium.xml
