<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 18:10:53.
 */
class EmployeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Employe
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Employe("Durand", 1000);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Employe::augmenteSalaire
     * @todo   Implement testAugmenteSalaire().
     */
    public function testAugmenteSalaire() {
        // Remove the following lines when you implement this test.
        $this->object->augmenteSalaire();
        self::assertEquals(1050, $this->object->getSalaire());
    }

}
